# Generated by Django 4.2.8 on 2024-01-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='on_auction',
            field=models.BooleanField(default=False),
        ),
    ]
