# Generated by Django 4.2.8 on 2024-01-17 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_bidder_auction_current_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
